// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIiCGIAqKOwq23cxQ24wVqo-ybUz5E1eg',
    appId: '1:475123206368:web:a9a16602aa4af76286a885',
    messagingSenderId: '475123206368',
    projectId: 'mahasainik-2c219',
    authDomain: 'mahasainik-2c219.firebaseapp.com',
    storageBucket: 'mahasainik-2c219.appspot.com',
    measurementId: 'G-HP8ZP0ZE5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5uCT9nf65WnQ5rJqdTxDQ_-zJL4qn-1g',
    appId: '1:475123206368:android:5d06e64f8bcb49ad86a885',
    messagingSenderId: '475123206368',
    projectId: 'mahasainik-2c219',
    storageBucket: 'mahasainik-2c219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyvI5kdZyG6h13S0LB4BOo5lOCSTWBeds',
    appId: '1:475123206368:ios:d126054b6651212186a885',
    messagingSenderId: '475123206368',
    projectId: 'mahasainik-2c219',
    storageBucket: 'mahasainik-2c219.appspot.com',
    iosClientId: '475123206368-hmvgbbt6cbvdb5tcouu3h87aq2qcc1d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahasainikApp',
  );
}
